#!/bin/bash

#Bash script that transfers a file from our client to a server

display_usage(){
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$#" -lt 4 ]; then
	display_usage
	exit 1
fi

./0-transfer_file some_page.html 8.8.8.8 sylvain /vagrant/private_key

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

scp -q -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
exit 0
