#!/bin/bash

#Bash script that transfers a file from our client to a server

echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp -q -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
